//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_sonnen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedWarranty
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SerialNumber { get; set; }
        public string ProductInstalled { get; set; }
        public int Capacity { get; set; }
        public System.DateTime InstallDate { get; set; }
        public Nullable<int> InstallerId { get; set; }
        public double Price { get; set; }
        public string ExtendedWarranty1 { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string BrainTreePaymentId { get; set; }
    
        public virtual Installer Installer { get; set; }
    }
}
